AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/SignalException:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false