apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  RAILS_ENV: "development"
  DATABASE_HOST: "db" # Имя нашего сервиса для PostgreSQL
  DATABASE_USER: "postgres"
  DATABASE_DB: "vue_blog_development"
