apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce # Монопольный доступ для одного пода (стандарт для БД)
  resources:
    requests:
      storage: 1Gi # Запрашиваем 1 гигабайт хранилища
